# Spring properties
spring:
  application:
     name: frontend-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port

zuul:
  routes:
    item:
      path: /item/*
      url: http://localhost:2222/item
      sensitive-headers: Cookie,Set-Cookie
    item-Admin:
      path: /item/admin/*
      url: http://localhost:2222/item/admin
      sensitive-headers: Cookie,Set-Cookie  
    category:
      path: /category/*
      url: http://localhost:2222/category
      sensitive-headers: Cookie,Set-Cookie
    auth:
      path: /oauth/*
      url: http://localhost:2222/oauth
      sensitive-headers: Cookie,Set-Cookie
    authority:
      path: /authority/*
      url: http://localhost:2222/authority
      sensitive-headers: Cookie,Set-Cookie
    api:
      path: /v2/*
      url: http://localhost:2222/v2
      sensitive-headers: Cookie,Set-Cookie
    item-api:
      path: /v2/item/*
      url: http://localhost:2222/item
      sensitive-headers: Cookie,Set-Cookie
    dashboard:
      path: /dashboard/*
      url: http://localhost:2222/dashboard
