# Spring properties
spring:
  application:
     name: frontend-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://178.62.122.61:8761/eureka/

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port

zuul:
  routes:
    item:
      path: /item/*
      url: http://178.62.122.61:2222/item
      sensitive-headers: Cookie,Set-Cookie
    item-Admin:
      path: /item/admin/*
      url: http://178.62.122.61:2222/item/admin
      sensitive-headers: Cookie,Set-Cookie  
    review:
      path: /review/*
      url: http://178.62.122.61:2222/review
      sensitive-headers: Cookie,Set-Cookie  
    shoppingCart:
      path: /shoppingCart/*
      url: http://178.62.122.61:2222/shoppingCart
      sensitive-headers: Cookie,Set-Cookie  
    category:
      path: /category/*
      url: http://178.62.122.61:2222/category
      sensitive-headers: Cookie,Set-Cookie
    auth:
      path: /oauth/*
      url: http://178.62.122.61:2222/oauth
      sensitive-headers: Cookie,Set-Cookie
    authority:
      path: /authority/*
      url: http://178.62.122.61:2222/authority
      sensitive-headers: Cookie,Set-Cookie
    api:
      path: /v2/*
      url: http://178.62.122.61:2222/v2
      sensitive-headers: Cookie,Set-Cookie
    item-api:
      path: /v2/item/*
      url: http://178.62.122.61:2222/item
      sensitive-headers: Cookie,Set-Cookie
    dashboard:
      path: /dashboard/*
      url: http://178.62.122.61:2222/dashboard
    customer:
      path: /customer/*
      url: http://178.62.122.61:2222/customer
      sensitive-headers: Cookie,Set-Cookie
    order-admin:
      path: /order/admin/*
      url: http://178.62.122.61:2222/order/admin
      sensitive-headers: Cookie,Set-Cookie
    order:
      path: /order/*
      url: http://178.62.122.61:2222/order
      sensitive-headers: Cookie,Set-Cookie
    recommender:
      path: /recommender/*
      url: http://178.62.122.61:2222/recommender
      sensitive-headers: Cookie,Set-Cookie
